### ISSUE TITLE
Operation `get_account_balances` missing

### ISSUE THREAD

**Issue by gcsolaroli** [tigerbeetle/tigerlings#6]
While working through the different steps, I have encountered a problem on step `014_get_account_balances.sh`.

After having "fixed" the script …

```
% git diff exercises/014_get_account_balances.sh 
diff --git a/exercises/014_get_account_balances.sh b/exercises/014_get_account_balances.sh
index a4267e0..2392d08 100755
--- a/exercises/014_get_account_balances.sh
+++ b/exercises/014_get_account_balances.sh
@@ -16,4 +16,4 @@ tb "create_transfers id=14000 debit_account_id=1400 credit_account_id=1401 amoun
                      id=14002 debit_account_id=1400 credit_account_id=1401 amount=100 ledger=140 code=10;"
 
 # Uh oh! We're trying to look up historical balances for an account that doesn't have history enabled.
-tb "get_account_balances account_id=1401;"
+tb "get_account_balances account_id=1400;"
```

it still fails to run

```
Running exercise: ./exercises/014_get_account_balances.sh
[Server] info(message_bus): connection from client 96979352940751237662583011120927243073
[Server] info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.replica).Connection.Peer{ .client = 96979352940751237662583011120927243073 }
[Client] info(message_bus): connected to replica 0
[Server] info(message_bus): connection from client 81308080956991366917894584661048530706
[Server] info(message_bus): peer performed an orderly shutdown: message_bus.MessageBusType(.replica).Connection.Peer{ .client = 81308080956991366917894584661048530706 }
[Client] info(message_bus): connected to replica 0
[Client] Fail near line 1, column 0:
[Client] 
[Client] get_account_balances account_id=1400
[Client] ^ Near here.
[Client] 
[Client] Operation must be help, create_accounts, lookup_accounts,
[Client] create_transfers, or lookup_transfers. Got: 'get_account_balances'.
```

I am using the Mac version of `tigerbeetle`, just download from the suggested [link](https://mac.tigerbeetle.com):
```
% ./tigerbeetle version
TigerBeetle version 0.15.3
```

The `get_account_balances` operation exists (at least in the [documentation](https://github.com/tigerbeetle/tigerbeetle/blob/main/docs/reference/requests/get_account_balances.md)) but seems to be missing from the binary I am using.

What am I doing wrong?

**Comment by batiati** [comment]
Hey @gcsolaroli thanks for catching the error in the script!

The REPL only started supporting `get_account_{transfers,balances}` after the stable release 0.15.3;  So you might want to build TigerBeetle from source to be able to use those functions from the command line. Note that it's only a REPL limitation: clients and the server itself have full support.

**Comment by gcsolaroli** [comment]
Thanks @batiati ; is there any plan for an updated stable release soon?
Otherwise I will try to build from source, even though I do not have any of the `zig` tooling installed.

**Comment by batiati** [comment]
> Thanks @batiati ; is there any plan for an updated stable release soon?

As soon we land the multiversion binary that will allow upgrades: https://github.com/tigerbeetle/tigerbeetle/pull/2013

If you want to give it a try, building from source is very simple (no pre-installed tooling other than git is required),  please see the documentation [here](https://github.com/tigerbeetle/tigerbeetle/blob/main/README.md#quickstart): 

```bash
git clone https://github.com/tigerbeetle/tigerbeetle && cd tigerbeetle
./scripts/install_zig.sh # or .bat if you're on Windows.
zig/zig build
./tigerbeetle version
```

**Comment by emschwartz** [comment]
You can uncomment the last set of instructions in the first exercise to build it from source https://github.com/tigerbeetle/tigerlings/blob/90f24a03887045cd1b821474e5d5cb9049ae0320/exercises/000_download.sh#L17-L22

**Comment by gcsolaroli** [comment]
I'll give it a try, thanks!

**Comment by gcsolaroli** [comment]
Builing `tigerbeetle` from source is really easy (props to `zig` for the smoothness of the process).
I had to delete the previous archive file, as the new version (that shows up as `0.0.1+0be1432`) was complaining about some versions not matching. Once the archive was recreated, everything else went very smoothly.
👏
